name: release-new-version

on: workflow_dispatch

permissions:
  contents: write

jobs:
  compile_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Typst
      run: |
        wget https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
        tar -xf typst-x86_64-unknown-linux-musl.tar.xz
        sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/

    - name: Get date
      id: get_date
      run: |
        echo "build_date=$(date +%Y.%m)" >> "$GITHUB_OUTPUT"

    - name: Compile Document
      run: |
        typst compile main.typ \
          --input version="${{ steps.get_date.outputs.build_date }}"
        ls -al # List files to check if main.pdf exists

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: 'v${{ steps.get_date.outputs.build_date }}'
        name: 'Release v${{ steps.get_date.outputs.build_date }}'
        draft: false
        prerelease: false
        files: main.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

